### ISSUE TITLE
运行 zhongguorenshou.py 无法通过

### ISSUE THREAD

**Issue by QQ2737499951** [langgithub/slide_img#2]
zhongguorenshou.py
{'captcha': {'backImg': '/hdyz/images_slide/jiabao/back.png', 'grapImg': '/hdyz/images_slide/jiabao/grap4.png', 'grayBackImg': '/hdyz/images_slide/jiabao/grayBack.png', 'serialNo': '29', 'slideImg': '/hdyz/images_slide/jiabao/slide4.png', 'slideX': '210', 'slideY': '17', 'validstatus': '1'}}
197
093f65e080a295f8076b1c5722a46aa293
197
<class 'str'> ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
588,589,590,591,592,594,596,599,602,606,610,614,620,626,633,640,648,656,666,676,686,696,706,715,723,730,738,744,749,754,759,763,766,769,771,773,775,776,777
378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378
1556381367177,1556381367185,1556381367194,1556381367202,1556381367210,1556381367219,1556381367227,1556381367236,1556381367244,1556381367253,1556381367261,1556381367269,1556381367276,1556381367284,1556381367292,1556381367299,1556381367306,1556381367314,1556381367322,1556381367330,1556381367338,1556381367346,1556381367354,1556381367361,1556381367369,1556381367376,1556381367384,1556381367392,1556381367400,1556381367407,1556381367415,1556381367423,1556381367431,1556381367439,1556381367448,1556381367457,1556381367465,1556381367473,1556381367481,1556381367488
http://busi.epicc.com.cn/slidecaptcha/checkCaptcha.code?challenge=093f65e080a295f8076b1c5722a46aa293&pageX=209&typeMouse=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&pageXAxis=588,589,590,591,592,594,596,599,602,606,610,614,620,626,633,640,648,656,666,676,686,696,706,715,723,730,738,744,749,754,759,763,766,769,771,773,775,776,777&pageYAxis=378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378,378&mouseTime=1556381367177,1556381367185,1556381367194,1556381367202,1556381367210,1556381367219,1556381367227,1556381367236,1556381367244,1556381367253,1556381367261,1556381367269,1556381367276,1556381367284,1556381367292,1556381367299,1556381367306,1556381367314,1556381367322,1556381367330,1556381367338,1556381367346,1556381367354,1556381367361,1556381367369,1556381367376,1556381367384,1556381367392,1556381367400,1556381367407,1556381367415,1556381367423,1556381367431,1556381367439,1556381367448,1556381367457,1556381367465,1556381367473,1556381367481,1556381367488&jsoncallback=jQuery111006172527293042014_1556084569011
jQuery111006172527293042014_1556084569011({"captcha":{"statusCode":"error"}})

**Comment by langgithub** [comment]
很久没有维护了，失效了
