### ISSUE TITLE
ImportError: cannot import name 'selenium_spider' from 'tools',麻烦问下怎么解决，谢谢

### ISSUE THREAD

**Issue by wentgithub** [langgithub/slide_img#3]
ImportError: cannot import name 'selenium_spider' from 'tools'

**Comment by langgithub** [comment]
只有v3文件下是正常，没有看见哪里用 了import name 'selenium_spider' from 'tools'

**Comment by wentgithub** [comment]
这个是一个单独的程序，不在打包里面，反正跑不通，别研究了
